### ISSUE TITLE
Error  display when run the command : docker-composer up

### ISSUE THREAD

**Issue by haymen** [adyassine/symfony4-docker#3]
![error-doc](https://user-images.githubusercontent.com/1176610/38140260-4dbc3af6-3433-11e8-95d8-aa5f9866a2c6.png)

**Comment by jbouzekri** [comment]
+1

**Comment by GuillaumeValadas** [comment]
Me too, apparently you got no answer ! :-1:

**Comment by adyassine** [comment]
@haymen @YouzOnline  @jbouzekri Fixed, the Dockerfile path was wrong
